//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.AccesoDatos
{
    using Dominio.Modelo.Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LABEntities : DbContext
    {
        public LABEntities()
            : base("name=LABEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<departamento_laboratorio> departamento_laboratorio { get; set; }
        public virtual DbSet<medico> medico { get; set; }
        public virtual DbSet<muestra> muestra { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<tipo_prueba> tipo_prueba { get; set; }
    }
}
