//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class muestra
    {
        public int id_muestra { get; set; }
        public Nullable<int> id_paciente { get; set; }
        public Nullable<int> id_medico { get; set; }
        public Nullable<int> id_tipo_prueba { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual departamento_laboratorio departamento_laboratorio { get; set; }
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
        public virtual tipo_prueba tipo_prueba { get; set; }
    }
}
